name: pull-request

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cross-build-pull-request-valgrind:
    runs-on: ubuntu-20.04
    container: vathpela/efi-ci:${{ matrix.distro }}-x64
    name: ${{ matrix.distro }} ${{ matrix.efiarch }} cross-build
    strategy:
      matrix:
        include:
          - arch: amd64
            efiarch: x64
            makearch: x86_64
            distro: centos8
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # otherwise we are testing target branch instead of the PR branch (see pull_request_target trigger)
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          submodules: recursive
      - name: install valgrind
        run: |
          dnf -y install valgrind
      - name: Update submodules on ${{ matrix.distro }} for ${{ matrix.efiarch }}
        id: update-submodules
        run: |
          make update
      - name: Do 'make clean' on ${{ matrix.distro }} for ${{ matrix.efiarch }}
        id: clean
        run: |
          make ARCH=${{ matrix.makearch }} PREFIX=/usr DESTDIR=/destdir EFIDIR=test ENABLE_SHIM_HASH=true clean
      - name: Run tests on ${{ matrix.distro }} for ${{ matrix.efiarch }}
        id: test
        run: |
          make ARCH=${{ matrix.makearch }} PREFIX=/usr DESTDIR=/destdir EFIDIR=test ENABLE_SHIM_HASH=true VALGRIND=valgrind test
      - name: Do the build on ${{ matrix.distro }} for ${{ matrix.efiarch }}
        id: build
        run: |
          make ARCH=${{ matrix.makearch }} PREFIX=/usr DESTDIR=/destdir EFIDIR=test ENABLE_SHIM_HASH=true all
      - name: Install on ${{ matrix.distro }} for ${{ matrix.efiarch }}
        id: install
        run: |
          make ARCH=${{ matrix.makearch }} PREFIX=/usr DESTDIR=/destdir EFIDIR=test ENABLE_SHIM_HASH=true install
          echo 'results:'
          find /destdir -type f
